# -*- coding: utf-8 -*-
"""plot_ablation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/nataliemonged/plot-ablation.20c6d2b8-4d39-46f9-b3e7-b1053f982be6.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260608/auto/storage/goog4_request%26X-Goog-Date%3D20260608T125114Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D240f382a702d0728de869be6abb197b60ebf86d8a0aefab2cbd563af0d79de81cad50bc50316e74d255db4095098fea8ff551d063a3080a0595564ea159808b8f7a145658cc9b360c95a5b520f0cc6b7b19e757d86f1f987dec2cf217bc0112c9a74371568d8d172edbdab06456ecb0605ef7d1214023e7e122b9ab0e1990f53bdd5ea1d65e0d23bd150ab3ea1b1ba0c4513aac0cbd27c66b36c7dd6aaa8aee3367b3eac036c3cf34411eebe565ce049184a58e223c1c058f9d621b6a64726881d8b2d2168664fc3c759d4e4ae196e950ac0ea3eb92ed989e7d9eddbe8680fc859ddec28fab3e178aa25a391a8a598fa4ef014de21d6efb8211d21c970826eb2
"""

#import's part
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import os

def main():
    # Configure plot aesthetics to meet IEEE academic publication standards
    # This ensures high readability, serif fonts, and appropriate scaling for papers
    sns.set_theme(style="whitegrid")
    sns.set_context("paper", font_scale=1.5)
    plt.rcParams.update({
        'font.family': 'serif',
        'axes.labelsize': 14,
        'xtick.labelsize': 12,
        'ytick.labelsize': 12,
        'legend.fontsize': 12,
        'axes.titlesize': 16,
        'figure.dpi': 300
    })
    # Define the structural augmentation configurations tested in the pipeline
    experiments = [
        "Exp 36\n(Pure Rotation)",
        "Exp 35\n(Weak Baseline)",
        "Exp 9\n(Crop + Blur)",
        "Exp 13\n(Crop+Flip+Blur)",
        "Exp 10\n(Crop + Cutout)"
    ]

    # Baseline Top-1 test accuracy metrics (models trained without color jitter)
    acc_without_jitter = [34.40, 59.22, 63.01, 64.49, 66.27]

    # Placeholders for upcoming experiments where color jitter is introduced
    # to prevent the model from relying on color histograms as a shortcut
    acc_with_jitter = [0.0, 0.0, 0.0, 0.0, 0.0]

    # Construct the dataset for seaborn, doubling the experiments list to match both conditions
    df = pd.DataFrame({
        'Experiment': experiments * 2,
        'Top-1 Accuracy (%)': acc_without_jitter + acc_with_jitter,
        'Condition': ['Base Augmentation\n(Without Color Jitter)'] * 5 + ['Base + Color Jitter\n(With Jitter)'] * 5
    })

    # Initialize the figure canvas with dimensions optimized for double-column papers
    fig, ax = plt.subplots(figsize=(11, 6.5))

    # Define a custom, colorblind-friendly palette to clearly contrast the two conditions
    palette = {"Base Augmentation\n(Without Color Jitter)": "#1f77b4", "Base + Color Jitter\n(With Jitter)": "#2ca02c"}

    # Render the grouped bar chart
    barplot = sns.barplot(
        data=df,
        x='Experiment',
        y='Top-1 Accuracy (%)',
        hue='Condition',
        palette=palette,
        edgecolor='black',
        linewidth=1.2,
        ax=ax
    )

    # Iterate through the generated bars to overlay exact accuracy percentages
    # This prevents the reader from having to guess values from the y-axis
    for p in barplot.patches:
        height = p.get_height()
        # Only label completed experiments (non-zero bars)
        if height > 0:
            ax.annotate(f'{height:.2f}%',
                        (p.get_x() + p.get_width() / 2., height),
                        ha='center', va='bottom',
                        xytext=(0, 5),
                        textcoords='offset points',
                        fontsize=11, fontweight='bold')

    # Apply descriptive labels, title, and strictly bound the y-axis to 100%
    ax.set_title('Impact of Color Jitter on Shortcut Learning in SimCLR\n(Linear Probe Top-1 Test Accuracy)', pad=20, fontweight='bold')
    ax.set_ylabel('Top-1 Test Accuracy (%)', fontweight='bold', labelpad=15)
    ax.set_xlabel('Structural Augmentation Strategy', fontweight='bold', labelpad=15)
    ax.set_ylim(0, 100)

    # Customize the legend to integrate seamlessly into the upper left without obscuring data
    ax.legend(title='', loc='upper left', bbox_to_anchor=(0.02, 0.98), framealpha=0.9, edgecolor='black', fancybox=True)

    # Adjust layout to prevent label clipping
    plt.tight_layout()

    # Export the finalized charts in both raster (PNG) and vector (PDF) formats
    out_png = 'ablation_shortcut_learning.png'
    out_pdf = 'ablation_shortcut_learning.pdf'
    plt.savefig(out_png, dpi=300, bbox_inches='tight')
    plt.savefig(out_pdf, bbox_inches='tight')
    print(f"Academic charts successfully saved to {out_png} and {out_pdf}")

if __name__ == "__main__":
    main()